services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=yourUserName
      - MINIO_ROOT_PASSWORD=yourStrongPassword123
    ports:
      - "9000:9000"
      - "9001:9001"       # обязательно добавить проброс порта для WebUI
    env_file:
      - .env
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    env_file:
      - .env
    environment:
      - REDIS_HOST=host
      - REDIS_PASSWORD=passsw123
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass 2571
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  minio-data:
  redis-data:
  db-data: